version: '3.8'

services:
  snipe-it:
    container_name: snipe-it
    image: snipe/snipe-it:latest
    ports:
      - "80:80"
    depends_on:
      - snipe-mysql
    mac_address: 02:42:c0:a8:84:48
    networks:
      x_vlan:
        ipv4_address: 192.168.16.48
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=base64:Sgw6+lgDo2BNC78M2vBdJYrwLroFW0TuXaWTM0l2C+g=
      - DB_CONNECTION=mysql
      - DB_HOST=snipe-mysql
      - DB_PORT=3306
      - DB_DATABASE=snipeit
      - DB_USERNAME=snipeit
      - DB_PASSWORD=sniptit
      - APP_URL=http://192.168.16.48
      - MAIL_DRIVER=smtp
      - MAIL_HOST=mail.anestia-life.fr
      - MAIL_PORT=465
      - MAIL_USERNAME=sae4d01@anestia-life.fr
      - MAIL_PASSWORD=vJ2@HWgbSCbsuPE
      - MAIL_ENCRYPTION=SSL
      - MAIL_FROM_ADDRESS=sae4d01@anestia-life.fr
      - MAIL_FROM_NAME=Inventaire_G1

  snipe-mysql:
    container_name: snipe-mysql
    image: mysql
    volumes:
      - ./data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    mac_address: 02:42:c0:a8:84:39
    networks:
      x_vlan:
        ipv4_address: 192.168.16.39
    environment:
      - MYSQL_ROOT_PASSWORD=iut
      - MYSQL_DATABASE=snipeit
      - MYSQL_USER=snipeit
      - MYSQL_PASSWORD=sniptit

networks:
  x_vlan:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
          gateway: 192.168.16.99
