version: '3'
services:
  unbound:
    container_name: unbound
    image: "mvance/unbound:latest"
    expose:
      - "53"
    network_mode: bridge
    ports:
     - "53:53/udp"
     - "53:53/tcp"
    mac_address: 02:42:c0:a8:84:41
    networks:
      x_vlan:
        ipv4_address: 192.168.16.41
    volumes:
      - ./my_conf/forward-records.conf:/opt/unbound/etc/unbound/forward-records.conf
      - ./my_conf/a-records.conf:/opt/unbound/etc/unbound/a-records.conf
    restart: unless-stopped

networks:
  x_vlan:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
          gateway: 192.168.16.99