version: '3.8'

services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=iut
      - MYSQL_DATABASE=iut
      - MYSQL_USER=iut
      - MYSQL_PASSWORD=iut
    networks:
      x_vlan:
        ipv4_address: 192.168.16.46

  nextcloud_app:
    image: nextcloud
    restart: always
    ports:
      - 80:80
    mac_address: 02:42:c0:a8:84:23
    networks: 
      x_vlan:
        ipv4_address: 192.168.16.45
    links:
      - nextcloud_db
    volumes:
      - ./data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db 
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=iut
      - MYSQL_PASSWORD=iut
networks:
  x_vlan:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
          gateway: 192.168.16.99
