version: '2.3'
services:
  redis:
    restart: always
    image: redis:6.2.6
    command:
    - --loglevel warning
    volumes:
    - ./redis-data:/data:Z
    networks:
      x_vlan:
        ipv4_address: 192.168.16.43
  postgresql:
    restart: always
    image: sameersbn/postgresql:12-20200524
    volumes:
    - ./postgresql-data:/var/lib/postgresql:Z
    environment:
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production
    - DB_EXTENSION=pg_trgm,btree_gist
    networks:
      x_vlan:
        ipv4_address: 192.168.16.42
  gitlab:
    restart: always
    image: sameersbn/gitlab:16.0.3
    depends_on:
    - redis
    - postgresql
    ports:
    - "80:80"
    - "22:22"
    mac_address: 02:42:c0:a8:84:44
    networks: 
      x_vlan:
        ipv4_address: 192.168.16.44
    volumes:
    - ./gitlab-data:/home/git/data:Z
    healthcheck:
      test: ["CMD", "/usr/local/sbin/healthcheck"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 5m
    environment:
    - DEBUG=false

    - DB_ADAPTER=postgresql
    - DB_HOST=postgresql
    - DB_PORT=5432
    - DB_USER=gitlab
    - DB_PASS=password
    - DB_NAME=gitlabhq_production

    - REDIS_HOST=redis
    - REDIS_PORT=6379

    - TZ=Europe/Paris
    - GITLAB_TIMEZONE=Paris

    - GITLAB_HTTPS=false
    - SSL_SELF_SIGNED=false

    - GITLAB_HOST=localhost
    - GITLAB_PORT=80
    - GITLAB_SSH_PORT=22
    - GITLAB_RELATIVE_URL_ROOT=
    - GITLAB_SECRETS_DB_KEY_BASE=mPnzx4k4PXLjCnFRfnKVHpcx9CWwhfmbbCxdjPncx7rvjxwbCxMpxXCNsMdmMffn
    - GITLAB_SECRETS_SECRET_KEY_BASE=mPnzx4k4PXLjCnFRfnKVHpcx9CWwhfmbbCxdjPncx7rvjxwbCxMpxXCNsMdmMffn
    - GITLAB_SECRETS_OTP_KEY_BASE=mPnzx4k4PXLjCnFRfnKVHpcx9CWwhfmbbCxdjPncx7rvjxwbCxMpxXCNsMdmMffn

    - GITLAB_ROOT_PASSWORD= YyeSRFRSTi4WfN7
    - GITLAB_ROOT_EMAIL= mathieu.puig@etu.umontpellier.fr

    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=true
    - GITLAB_NOTIFY_PUSHER=false

    - GITLAB_EMAIL=mathieu.puig@etu.umontpellier.fr
    - GITLAB_EMAIL_REPLY_TO=mathieu.puig@etu.umontpellier.fr
    - GITLAB_INCOMING_EMAIL_ADDRESS=mathieu.puig@etu.umontpellier.fr

    - GITLAB_BACKUP_SCHEDULE=daily
    - GITLAB_BACKUP_TIME=01:00
networks:
  x_vlan:
    driver: macvlan
    driver_opts:
      parent: ens18
    ipam:
      driver: default
      config:
        - subnet: 192.168.16.0/24
          gateway: 192.168.16.99
